/* This file is autogenerated by cbindgen. Don't modify this manually. */

/**
 *[clinic input] _base64.b64encode
 *
 *    source: buffer     /
 *
 *Encode bytes-like object s using the standard Base64 alphabet.
 *
 *The result is returned as a bytes object. [clinic start generated code]
 */
PyObject *standard_b64encode(PyObject *_module, PyObject **args, Py_ssize_t nargs);

int _base64_clear(PyObject *_obj);

void _base64_free(void *_o);

PyObject *PyInit__base64(void);
