use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");

    let output_file = PathBuf::from(&crate_dir).join("_base64.rs.h");

    // Configure cbindgen
    let mut config = cbindgen::Config::default();
    config.language = cbindgen::Language::C;
    config.cpp_compat = false;
    config.no_includes = true;
    config.autogen_warning = Some("/* This file is autogenerated by cbindgen. Don't modify this manually. */".to_owned());

    // Generate C header file using cbindgen with config
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings with cbindgen")
        .write_to_file(&output_file);

    println!("cargo:rerun-if-changed=src/lib.rs");
}
